stage1/Stage1.scala, stage2/AdminStage2.scala, stage2/Stage2.scala
Some suggestions for #25. Probably some more things I'll fine when I get another chance to sit down and tinker with it, but I wanted to open early and provide some opportunity for feedback before I've invested a day in it. :grin:
=> Some style cleanups in Stage1.

stage1/Stage1.scala, stage1/logger.scala, stage2/Stage2.scala
Cleaning up stage 2 and the logger as I learn and start to understand it. :)
Refs #25
=> Stage 2 / Logger cleanups.

bootstrap_scala/BootstrapScala.java, cbt
Now able to bootstrap on JDK7, but I am unable to verify completely due to #54 
How is that CI coming along? :)
Not sure whether to keep any JDK version check in launcher script. Is JDK6 a target?
=> Rewrite Java 8 code in BootstrapScala.java in Java 7

README.md
=> Format README as markdown

nailgun_launcher/NailgunLauncher.java, stage1/Stage1Lib.scala, stage1/resolver.scala, stage2/BasicBuild.scala, stage2/BuildDependency.scala, stage2/Lib.scala
=> exit code fixes etc

LICENSE.txt
Following @fommil's advise I would like to change the license to Apache 2.0 
https://github.com/cvogt/cbt/issues/27
I'd like confirmation from all past (and very near future) contributors they are ok with this.
Confirmed: @tobias-johansson @farmdawgnation @hntd187 @paulp 
Pending confirmation: @tpolecat @chavxo @katrinsharp
Could you please confirm below?
Thx guys :)
=> Change License to Apache 2.0

stage1/Stage1.scala, stage1/logger.scala, stage1/resolver.scala, stage2/GitDependency.scala, test/simple/Main.scala, test/simple/build/build.scala
=> Add support for git dependencies

stage2/AdminStage2.scala, stage2/AdminTasks.scala, stage2/BasicBuild.scala, stage2/Scaffold.scala
this generates a build.scala file template
=> make scaffold work for simple case

README.md, TODO.txt, build/build.scala, circle.yml, nailgun_launcher/CBTUrlClassLoader.java, nailgun_launcher/EarlyDependencies.java, nailgun_launcher/NailgunLauncher.java, nailgun_launcher/Stage0Lib.java, stage1/MavenRepository.scala, stage1/Stage1.scala, stage1/Stage1Lib.scala, stage1/logger.scala, stage1/resolver.scala, stage2/AdminTasks.scala, stage2/BasicBuild.scala, stage2/BuildBuild.scala, stage2/BuildDependency.scala, stage2/GitDependency.scala, stage2/Lib.scala, stage2/SbtDependencyDsl.scala, stage2/Stage2.scala, stage2/mixins.scala, test/simple/build/build.scala, test/test.scala
there is still a severe but probably very easy to fix bug in the latest commit, which leads to basically CBT fundamentally not working, i.e. not finding Build classes or Build classes not finding cbt. Will fix tomorrow.
cc @tpolecat
=> Support for alternative maven resolvers

.gitignore, README.md, examples/build-scalajs/README.md, examples/build-scalajs/build/build.scala, examples/build-scalajs/build/build/build.scala, examples/build-scalajs/js/src/main/scala/App.scala, examples/build-scalajs/js/src/main/scala/Pictures.scala, examples/build-scalajs/server/app.js, examples/build-scalajs/server/package.json, examples/build-scalajs/server/public/index.html, examples/build-scalajs/shared/src/main/scala/prototype/Picture.scala, plugins/scalajs/ScalaJs.scala, plugins/scalajs/ScalaJsInformation.scala, plugins/scalajs/build/build.scala, stage1/Stage1Lib.scala, stage2/BasicBuild.scala, test/simple-fixed/build/build.scala, test/simple/build/build.scala, test/test.scala
Cross project support + example build with running example showing how to use it. Please 'missing features' in README for list of what missing. Counterparts of all missing features reside in Scalajs SBT plugin. We will need to port the associated code here. I prefer to move with this pull request first since it enables working scalajs build as shown in build example.
=> scalajs cross project support as plugin

examples/scalariform-example/README.md, examples/scalariform-example/build/build.scala, examples/scalariform-example/build/build/build.scala, examples/scalariform-example/resources/reference.conf, examples/scalariform-example/src/Main.scala, plugins/scalariform/Scalariform.scala, plugins/scalariform/build/build.scala, stage2/BuildBuild.scala
=> Scalariform support

examples/scalafmt-example/README.md, examples/scalafmt-example/build/build.scala, examples/scalafmt-example/build/build/build.scala, examples/scalafmt-example/resources/reference.conf, examples/scalafmt-example/src/Main.scala, examples/scalariform-example/README.md, examples/scalariform-example/build/build.scala, plugins/scalafmt/Scalafmt.scala, plugins/scalafmt/build/build.scala, plugins/scalariform/Scalariform.scala, stage1/logger.scala, stage2/BuildBuild.scala, test/test.scala
=> Scalafmt plugin implementation

examples/multi-project-example/build/build.scala, examples/multi-project-example/build/build/build.scala, examples/multi-project-example/common/SomeSharedClass.scala, examples/multi-project-example/common/build/build.scala, examples/multi-project-example/common/build/build/build.scala, examples/multi-project-example/shared-build/SharedCbtBuild.scala, examples/multi-project-example/shared-build/build/build.scala, examples/multi-project-example/sub1/SomeConcreteClass.scala, examples/multi-project-example/sub1/build/build.scala, examples/multi-project-example/sub1/build/build/build.scala, examples/multi-project-example/sub2/SomeOtherConcreteClass.scala, examples/multi-project-example/sub2/build/build.scala, examples/multi-project-example/sub2/build/build/build.scala, test/test.scala
=> add multi-project example

cbt, nailgun_launcher/NailgunLauncher.java, nailgun_launcher/Stage0Lib.java, stage1/Stage1Lib.scala, stage2/Lib.scala
Proxy settings can be supplied either via Java systemproperties or via
environment variables (http_proxy / https_proxy). Java systemproperties
take precedence over env vars.
Evaluation of proxy settings happens only during nailgun startup for now.
=> Support proxy settings in CBT.

stage2/BasicBuild.scala, stage2/Lib.scala, test/test.scala
fixes https://github.com/cvogt/cbt/issues/38
=> `clean` task

examples/wartremover-example/build/build.scala, examples/wartremover-example/build/build/build.scala, examples/wartremover-example/src/Main.scala, plugins/wartremover/WartRemover.scala, plugins/wartremover/build/build.scala, stage2/BuildBuild.scala, test/test.scala
=> WartRemover plugin implementation

plugins/scalafmt/Scalafmt.scala, plugins/scalafmt/build/build.scala
=> Upgrade scalafmt 0.2.5 -> 0.3.1

circle.yml, examples/dotty-example/README.md, examples/dotty-example/build/build.scala, examples/dotty-example/src/Main.scala, stage1/Stage1Lib.scala, stage2/plugins/Dotty.scala, test/simple-fixed/build/build.scala, test/simple/build/build.scala, test/test.scala
First working version. @felixmulder, please review or pull in who needs to see this.
(Fixed the issue I had earlier. Remembered I used to have the same with scalac some time ... scala library was not on the cp).
=> Dotty plugin and example project.

stage2/Scaffold.scala
=> minor enhancements to Build template

stage1/Stage1Lib.scala
Fixes error message in pickOne function
=> fix pickOne error message

stage2/BasicBuild.scala, stage2/plugins/Dotty.scala
Added task for project-aware REPL. Uses project's classpath and project's scala version
=> repl task in BaseBuild

README.md
Updated to reflect proper usage of 'it's' vs 'its'
- "It's" = contraction (i.e. "it is")
- "Its" = possessive
=> Updated to reflect proper usage of "it's" vs "its"

README.md, build/build.scala, cbt, compatibility/Context.java, examples/build-info-example/build/build.scala, examples/dynamic-overrides-example/build/build.scala, examples/sonatype-release-example/build/build.scala, libraries/eval/build/build/build.scala, plugins/essentials/CommandLineOverrides.scala, plugins/essentials/DynamicOverrides.scala, plugins/essentials/PublishDynamic.scala, plugins/essentials/Readme.md, plugins/essentials/build/build.scala, stage1/ContextImplementation.scala, stage1/Stage1.scala, stage1/cbt.scala, stage1/constants.scala, stage1/logger.scala, stage1/resolver.scala, stage2/BasicBuild.scala, stage2/BuildBuild.scala, stage2/Lib.scala, stage2/PackageJars.scala, stage2/Publish.scala, stage2/Stage2.scala, test/library-test/build/build.scala, test/simple-fixed-cbt/build/build.scala, test/simple-fixed/build/build.scala, test/simple/build/build.scala, test/test.scala
this branch will eventually fix https://github.com/cvogt/cbt/issues/62
=> Dynamic overrides

examples/dynamic-overrides-example/build/build.scala, plugins/essentials/DynamicOverrides.scala
=> enhance dynamic override to not use codegen when possible

stage1/resolver.scala, stage2/ToolsTasks.scala
Addresses problem brought up in #322.
=> Remove classifier from pom files.

cbt
fixes bugs / improves usability
=> Enhance bash script

README.md
SBT isn't an acronym, it's a proper name. Like iPhone or eBay.
=> Replace SBT with sbt

stage2/plugins/Frege.scala
=> fix merge-conflict in Frege plugin

stage1/resolver.scala
Handling recursive substitutions, e.g. in pom of `"com.amazonaws" % "aws-java-sdk-s3" % "1.11.86"` because `${awsjavasdk.version}` is being replaced with another variable: `${project.version}`
See: https://github.com/cvogt/cbt/issues/434
=> recursive pom variable substitution

README.md
=> fix eval example

tools/gui/resources/web/definitions.js, tools/gui/resources/web/index.html, tools/gui/resources/web/main.js, tools/gui/resources/web/styles.css
[live example](https://tim-zh.github.io/cbt_playground/1.html)
=> Fix #421 Html notifications

stage2/plugins/Scalameta.scala
May need some tests but for now it downloads the specified version of scalameta as long as it's available ;)
=> Make scalameta-version configurable

examples/export-build-information/Main.scala, examples/export-build-information/build/build.scala, examples/export-build-information/build/build/build.scala, stage2/BasicBuild.scala, stage2/plugins/ExportBuildInformation.scala
=> Export build information

examples/kindprojector-example/Main.scala, examples/kindprojector-example/build/build.scala, stage2/plugins/KindProjector.scala, test/test.scala
@cvogt is this all there is to do?
=> Added a cbt plugin for the kind-projector compiler plugin

examples/export-build-information/expected.xml, stage2/plugins/ExportBuildInformation.scala
Will work with IDEA when #536 will be accepted
=> Get rid of compiling CBT sources to jars

plugins/scalafmt/Scalafmt.scala
Currently, `scalafmt` only searches for `.scalafmt.conf` in `projectDirectory`. This doesn't work well for multi-module projects where there's only one `.scalafmt.conf` in root directory.
This PR changes search logic so that it first searches for .scalafmt.conf in all parent directories (not just `projectDirectory`), then fallbacks to home directory, and then fallbacks to default config.
Code by @cvogt on Gitter: https://gitter.im/cvogt/cbt?at=5a41021f0163b0281078c1a5
=> Scalafmt - .scalafmt.conf lookup

README.md, doc/intellij-gsoc.md
And please don't remove intellij-gsoc.md, let's leave it as gsoc legacy 
^_^
=> Update intellij doc
