stage1/Stage1Lib.scala

lead to half compiled sets of class files after a type
error and no attempt to re-compile unless a source file
is changed.
This workaround fixes it but needs to run zinc more often
which comes with a roughly 0.1 seconds time penalty every
time (despite classloader caching) for every involved sub build.
A fix would trep zinc's exit code (or call zinc differently)
in order to determine if it succeeded and if it did not
do something that makes it run again the next time, like
deleting the class files or touching a source file.
Probably there is a better way.

The condition disables zinc too eagerly, which can easily

---

cbt

Proposed fix for #42 
Checks javac version requirement in launcher script and exits with an error message if not fulfilled.
```
> javac -version 
javac 1.7.0_95
> cbt run
You need to install javac version 1.8 or greater! CBT currently relies on Java 8.
Current javac version is 1.7.0_95
```
Tested on Ubuntu, but not on OS X

Print error message if javac version < 1.8

---

stage1/KeyLockedLazyCache.scala
stage1/resolver.scala

This is what I came up with for concurrent builds in CBT. I realized last minute that we probably don't need the KeyLockedLazyCache, if we just use member-level caching again. I commented it out for now. Opinions?

A draft implementation that runs builds concurrently

---

README.md
coursier/Coursier.scala
stage1/Stage1Lib.scala
stage1/constants.scala
stage1/resolver.scala
stage2/AdminTasks.scala
stage2/BasicBuild.scala
stage2/BuildDependency.scala
stage2/PackageBuild.scala
test/simple/build/build.scala
test/test.scala

Add
- Constructor syntax for cross-scala-version dependencies (as rightfully requested on reddit) and encouraged over SBT's still supported operator syntax
- Add support for classifiers other than "sources"

Improved how to express dependencies

---

stage1/Stage1Lib.scala
stage2/BasicBuild.scala
stage2/Lib.scala
stage2/PackageBuild.scala
stage2/PublishBuild.scala
stage2/Stage2.scala
stage2/mixins.scala
test/simple/build/build.scala

Adds support for cross building for multiple scala versions
And for automatically appending -SNAPSHOT to the id, when publishing a snapshot.

cross building and automatic snaphot ids

---

stage2/Lib.scala
stage2/Publish.scala

This enables to publish into a repository where no credentials are
required but and empty/wrong HTTP Auth header throws an HTTP 401
(not authorized) error

Allow empty credentials for publishing.

---

circle.yml

for some reason the circle machines now have a .gitconfig that breaks jgit
it replaces https github urls with ssh github urls in a way jgit does not like

try to fix circleci

---

examples/scalafmt-example/.scalafmt.conf
examples/scalafmt-example/build/build.scala
examples/scalafmt-example/src/Main.scala
plugins/scalafmt/Scalafmt.scala
plugins/scalafmt/build/build.scala

Did some improvements to scalafmt plugin. Now, it uses config from .scalafmt.conf by default, as it does sbt-plugin and IDEA plugin.

upgrade scalafmt 0.3.1 -> 0.4.2; load scalafmt config from config file

---

cbt

Tried to improve plain JVM(no nailgun) startup time by applying common advices.
Info taken from here,:
https://jkutner.github.io/2015/12/01/java-boot-time.html#other-options-with-side-effects
https://github.com/jruby/jruby/wiki/Improving-startup-time#use-the-client-mode-of-the-jvm
Results on my laptop: 
java -version:
```
➜  cbt-args java -version
java version "1.8.0_72"
Java(TM) SE Runtime Environment (build 1.8.0_72-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.72-b15, mixed mode)
```
before:
```
➜  cbt-args time cbt foo
cbt foo  1.59s user 0.22s system 163% cpu 1.106 total
➜  cbt-args time cbt foo
cbt foo  1.58s user 0.21s system 176% cpu 1.018 total
➜  cbt-args time cbt foo
cbt foo  1.63s user 0.20s system 173% cpu 1.056 total
➜  cbt-args time cbt foo
cbt foo  1.62s user 0.22s …
```

Attempt to improve jvm startup time

---

.gitignore
cbt
compatibility/Context.java
doc/docs.md
nailgun_launcher/NailgunLauncher.java
stage1/ContextImplementation.scala
stage1/Stage1.scala
stage1/Stage1Lib.scala
stage1/cbt.scala
stage2/BasicBuild.scala
stage2/BuildBuild.scala
stage2/BuildDependency.scala
stage2/Lib.scala
stage2/Stage2.scala
test/test.scala

now CBT and builds pass their file names to the current build via the context. The build then simply blocks until any file changes. Then it returns with a special exit code, which the bash script picks up and restarts CBT. Thats works well for looping over project files. It works less well for looping over builds and CBT itself. For this a build has to success once, so that the .cbt-loop.tmp file exists. Then looping works for cbt and builds, but the file list is not updated in case of compile errors, etc.
Fixes
- https://github.com/cvogt/cbt/issues/406
- https://github.com/cvogt/cbt/issues/405
- https://github.com/cvogt/cbt/issues/202
- https://github.com/cvogt/cbt/issues/50
- https://github.com/cvogt/cbt/issues/22
We should improve for 1.0 in https://github.com/cvogt/cbt/issues/419
to …

revamp loop feature

---

DEVELOPER_GUIDE.txt
README.md
build/build.scala
cbt
compatibility/BuildInterface.java
compatibility/Context.java
doc/cbt-developer/version-compatibility.md
nailgun_launcher/NailgunLauncher.java
stage1/ContextImplementation.scala
stage1/Stage1.scala
stage1/Stage1Lib.scala
stage1/cbt.scala
stage1/resolver.scala
stage2/BasicBuild.scala
stage2/BuildBuild.scala
stage2/BuildDependency.scala
stage2/GitDependency.scala
stage2/Lib.scala
stage2/Stage2.scala
test/test.scala

last file watching update didn’t work well enough. This now
- rips out barbary watch service as it seems buggy crashing the jvm
- make cbt exclusively write files to watch to a file
- uses fswatch instead watching all files in that file
fixes #428 
fixes #419 
fixes #418

fix file watching for real

---

cbt

Installing nailgun via apt on Debian copies the server jar to
/usr/share/java/nailgun-server.jar. This change enables the sbt
launcher to find the jar.

Find nailgun-server jar on Debian

---

build/build.scala
doc/src/tut/example.md

Need to make a few tweaks to **tut** so we can call it in-process more cleanly, but this does work. I'm not sure what we want to have on the classpath here or how to get it; I'm just sending the `dependencyClasspath` for now.
Note that in real life we will need to run in a new classloader with the target version of scala and so forth. Baby steps. It's much much easier than calling from sbt.

tut proof of concept

---

plugins/scalapb/ScalaPB.scala

ScalaPB options were never used and were not in underscore case.
It has been tested with no options and it works (i.e. `--scala_out=<empty>:<path>`).

Fix ScalaPB options definition

---

NOTICE
stage2/plugins/Ensime.scala

This plugin adds the capability to generate ENSIME configuration files. It's settings are mostly copied from sbt-ensime.
Currently, only configuration for single-project builds is generated. I'll need to look deeper into how I can list a build's DirectoryDependencies, in order add support for multi-module projects.
Closes #89 
FYI @fommil

Add support for generating ensime configuration file

---

tools/gui/src/Main.scala

I'm using the Windows Subsystem for Linux in my adventures with CBT - and it runs headless, which the GUI tool (up till now) finds surprising and chokes on. This very humble small commit fixes that.

Fix gui summoning browser in headless mode

---

stage2/plugins/Ensime.scala

I've started using CBT on my free time (please keep up the good fight) and wanted to get some editor integration. Managed to make it ensime-atom pick the config by applying those changes. 
* This aims at facilitating picking the version for ensime server through overriding
* Bumped the version to 2.0.0-M4 (see https://github.com/ensime/ensime-server/releases)

Factored out ensimeServerVersion in the Ensime plugin

---

cbt.bat
libraries/process/process.scala
nailgun_launcher/src/cbt/EarlyDependencies.java
nailgun_launcher/src/cbt/NailgunLauncher.java
stage1/CbtPaths.scala
stage1/ClassPath.scala
stage1/Stage1.scala
stage2/ToolsTasks.scala

This PR fixes most of the issues with using CBT on Windows:
- cache strings are now *platform independent* as far as they can, by using `pip(unixPath: String)` (path-independent-path, just converts slashes to backslashes)
- batch script is now working properly and is *usable*
Some minor issues left:
- improve Nailgun support, `java.net.SocketException: Connection reset`
- time function
- nailgun log files are impossible to write to, when ng-server is up (`.. >> %nailgun_out% 2>> %nailgun_err%`)
- `eval` can't be used with single-quotes since CMD treats them specially... You can use double-quotes but then you can't use `String` literals 😄

Windows script fix

---

cbt

Support of relative symlinks to the cbt executable has been implemented.

---

libraries/reflect/reflect.scala

Possible fix for #585. Classes with non-public or parameterized contructors were made to be not searched by the main class searcher. This leads to
- not failing when project contains such class (with non-public or parameterized constructor and ``def main(args: Array[String])`` at the same time);
- ignoring such classes when searching a main-class, in particular, not showing such classes when there are alternatives.
And, oh, I changed the signature of the ``typeStaticMethod``, but I hope I made it more correct (since, as far as I can see, you use -``OrFail`` suffix for those methods you are expecting to be easily failing).

Classes with non-trivial constructors were made to be not considered as possible main classes
